# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn ng build --prod
      - run: yarn ng test --watch=false

      # - run :
      #     command: |
      #     docker build -t naveensprofile.azurecr.io/naveenr:1.0 .

      # - run :
      #     command: |
      #    # docker login --username NaveensProfile --password LkJkB9+MIEY72Z65N8nn3mY6m0wu20Ia naveensprofile.azurecr.io
      #     docker login --username $DOCKER_USER --password $DOCKER_PASS naveensprofile.azurecr.io
      #  - run :
      #     command: |
      #     docker push naveensprofile.azurecr.io/naveenr:1.0
